apiVersion: 1

datasources:
  - name: influxdbv2-influxql
    type: influxdb
    access: proxy
    url: http://$DOCKER_INFLUXDB_HOST:$DOCKER_INFLUXDB_PORT
    jsonData:
      dbName: $DOCKER_INFLUXDB_INIT_BUCKET
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: Token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      
